version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    ports:
      - "5000:8080"
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo:27017
      MONGO_DB_NAME: aytugdb
    depends_on:
      - mongo
volumes:
  mongo-data:
