version: "3.8"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017" # Optional: expose MongoDB for local access

  backend:
    build:
      context: ../backend
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS: http://+:8080
      MONGO_CONNECTION_STRING: mongodb://mongo:27017
      MONGO_DB_NAME: aytugdb
      # CORS origins (comma-separated). Override in Portainer if needed.
      CORS_ORIGINS: ${CORS_ORIGINS:-http://161.97.97.216:4000,http://aytugeren.com,https://aytugeren.com,http://www.aytugeren.com,https://www.aytugeren.com}
      # Writes new/updated post JSON here so web can serve it
      JSON_DIR: /app/public/generated/post
      # Optional: where to mirror MDX files inside the container
      CONTENT_DIR: /app/content/posts
      # JWT + Admin auth (set these in Portainer)
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER:-aytug-blog}
      JWT_AUDIENCE: ${JWT_AUDIENCE:-aytug-blog}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      GITHUB_USER: ${GITHUB_USER:-}
    depends_on:
      - mongo
    ports:
      - "4001:8080"
    volumes:
      - ../content:/app/content
      - generated-posts:/app/public/generated/post

  web:
    build:
      context: ..
      dockerfile: Dockerfile.web
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-}
      # No PNPM; Dockerfile handles npm and env
    restart: unless-stopped
    environment:
      NODE_ENV: production
      # Use same-origin API via Nginx at /api
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-}
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-}
      # Server-side only (not exposed to client)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    depends_on:
      - backend
    ports:
      - "4000:3000"
    volumes:
      # Share generated post JSON so Next can serve it at runtime
      - generated-posts:/app/public/generated/post:ro

  # No built-in proxy; use your Nginx Proxy Manager

volumes:
  mongo-data:
  generated-posts:
